### ISSUE TITLE
spaces in field names crash generateSchema

### ISSUE THREAD

**Issue by odama626** [FlatbreadLabs/flatbread#38]
spaces in field names currently causes composeWithJson to crash with obscure errors

we should map over the keys of json and camelCase all of the field names before composing it to prevent the errors,  we could maybe expose a config setting to allow accepting a string transform function if camelCase doesn't work for a user.

quick fix in the meantine

```js
function generateJSON<T>(collection: string, nodes: T[]) {
    const result = defaultsDeep(
      {},
      getFieldOverrides(collection, config),
      ...nodes.map((node) => merge({}, node, preknownSchemaFragments))
    );
    return JSON.parse(
      JSON.stringify(result, (key, value) => {
        if (typeof value === 'object') {
          return mapKeys(value, (key) => camelCase(key));
        }
        return value;
      })
    );
  }

  const schemaArray = Object.fromEntries(
    Object.entries(allContentNodesJSON).map(([collection, nodes]) => [
      collection,
      composeWithJson(collection, generateJSON(collection, nodes), {
        schemaComposer,
      }),
    ])
  );
  ```

**Comment by tonyketcham** [comment]
Great find - we can definitely add a validation function to format all field names

**Comment by Sheharyar566** [comment]
Should the exposed config be a part of the transformer interface? Or should be available directly on the config object (by the config object, I mean the destructured object received at line 34 in packages/core/src/generators/schema.ts file)?

Rather than implementing a seperate loop, I was thinking of transforming the key inside the Object.entries(......).map 🤔
